name: Deploy Zola to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and Deploy
        uses: shalzz/zola-deploy-action@v0.22.1
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
